version = 0.1

[default.global.parameters]
stack_name = "plate-detector-upload"
region = "us-east-1"

[default.build.parameters]
cached   = true
parallel = true

[default.deploy.parameters]
capabilities      = "CAPABILITY_IAM"
confirm_changeset = true
region            = "us-east-1"
resolve_s3        = true
parameter_overrides = "BucketName=\"plate-dataset-uploads\" AdminPrincipalArn=\"arn:aws:iam::826077735947:user/plate-detector-admin\" PresignedUrlExpirySeconds=\"3600\" StageName=\"prod\""
s3_prefix = "plate-detector-upload"
image_repositories = []
